### ISSUE TITLE
Reload Components?

### ISSUE THREAD

**Issue by antoine3000** [very-simple/components#9]
First of all, thanks for the library, it helps me stay organised and see me code clearly, thanks!

I use Barbajs to make transitions between my pages, so I need an event to restart the scripts. I've tried running `mountComponents()` each time a new page is launched, but it doesn't work. Is there a way to update the components? Or unmount/remount them?

Cheers!

**Comment by arnoson** [comment]
Glad to her that someone else is using this library :)

I've never used Barbajs (looks cool thou). When a component is mounted it adds an `$component` property on the HTML element. This tells the library that the component is already mounted and shouln't be mounted again. I'm not sure how exactly barbajs works, but maybe the DOM is somehow merged and not fully replaced, therefore the old HTML elements stay intact and won't get remounted. Normally, if a page visit loads new DOM content the `mountComponents()` should work.

You could force to remount the components by searching for all components and removing the `$component` before you call `mountComponents()`, like:
```js
document.querySelectorAll('[data-simple-component]').forEach(el => el.$component = undefined)
```

Or maybe barba.js exposes some kind of event system and you could notify your components manually?
Maybe like they show in the [custom code section](https://barba.js.org/docs/getstarted/custom-code/)

```js
// menu.js
export default registerComponent('menu', () => {
  // ...

  const update = () => {
    // do stuff when the page changes
  }

  return { update }
})


// index.js
barba.init({
  views: [{
    namespace: 'home',
    afterEnter() {
      const menu = document.querySelector('[data-simple-component="menu"]')
      menu.$component.update()
    }
  }]
});
```

If you have many components that need an update it might also be useful to use a simple event bus.
(Haven't tested this code above)

If you can provide a simplified repository with your setup I can look into it!

**Comment by antoine3000** [comment]
Thanks for your reply! Reading you, I realised that my component was not inside my Barba container and therefore did not have the Barba mechanics. So I placed my interactive `Nav` in the Barba box and it works like a charm.

Thanks again!

Here's my code for reference.

```
<body class="no-js body--<?= $page->template()->name() ?>" data-barba="wrapper">
  <snippet:header />
  <main class="main" id="main" data-barba="container" data-barba-namespace="page">
    <snippet:nav />
    <?= $slots->default() ?>
  </main>
  <snippet:footer />
</body>
```
